task:
  name: "PixelOS panther A14 Build"
  container:
    image: cirrusci/android-sdk:latest
  env:
    GIT_USERNAME: "ONLY1WAY2DIE"
    GIT_EMAIL: "dev@only1way2die.example"
    DEVICE: "panther"
    ROM_MANIFEST: "https://github.com/PixelOS-AOSP/manifest"
    ROM_BRANCH: "uvite"
    BUILD_TYPE: "userdebug"
    GDRIVE_FOLDER_ID: "<1uTqa6T4EhTzn80VOPsEUfczDcdHLsNTK>"
  script:
    - apt-get update && apt-get install -y repo git-core curl zip unzip python3 python3-pip
    - pip3 install gdown
    - mkdir -p ~/android/rom && cd ~/android/rom
    - git config --global user.name "$GIT_USERNAME"
    - git config --global user.email "$GIT_EMAIL"
    - repo init -u $ROM_MANIFEST -b $ROM_BRANCH --depth=1
    - mkdir -p .repo/local_manifests
    - curl -L "https://raw.githubusercontent.com/ONLY1WAY2DIE/pixelos-panther-a14/main/local_manifests/pixelos_panther_a14.xml" -o .repo/local_manifests/pixelos_panther_a14.xml
    - repo sync -j4
    - source build/envsetup.sh
    - lunch aosp_panther-$BUILD_TYPE
    - mka bacon
    # Ergebnis hochladen:
    - |
      ZIP=$(ls out/target/product/panther/*.zip | head -n 1)
      pip3 install --upgrade gdown
      gdown upload --folder $GDRIVE_FOLDER_ID "$ZIP"
